version = 1
disable_existing_loggers = false

[formatters.default]
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[handlers.stdout]
class = "logging.StreamHandler"
formatter = "default"
level = "DEBUG"
stream = "ext://sys.stdout"

[handlers.stderr]
class = "logging.StreamHandler"
level = "WARNING"
formatter = "default"
stream = "ext://sys.stderr"

[loggers.root]
level = "DEBUG"
handlers = ["stdout"]