import ctypes
import sys


def create_bat_file():
    from brightify.scripts.windows.add_startup_task import bat_file
    print(bat_file)
    # create a bat file to run the script
    content = \
        f"""
:: This script is generated by Brightify
@echo off
:: Run the brightify script
python.exe -m brightify
pause
exit
    """
    with open(bat_file, 'w+') as f:
        f.write(content)


def elevated_add_startup_task():
    create_bat_file()
    from brightify.scripts.windows import add_startup_task
    ctypes.windll.shell32.ShellExecuteW(None,  # hwnd
                                        "runas",  # operation
                                        sys.executable,  # program, the python interpreter
                                        add_startup_task.__file__,  # script to run
                                        None,  # working directory
                                        1)  # show window


def elevated_remove_startup_task():
    from brightify.scripts.windows import remove_startup_task
    ctypes.windll.shell32.ShellExecuteW(None,  # hwnd
                                        "runas",  # operation
                                        sys.executable,  # program, the python interpreter
                                        remove_startup_task.__file__,  # script to run
                                        None,  # working directory
                                        1)  # show window
